pipeline {
    agent any

    environment {
        DOCKER_HUB_REPO = 'vinayak2410/practice-11'
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/madgundi/practice-11.git', branch: 'main'
            }
        }

        stage('Build Java Application') {
            steps {
                dir('practice-11') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t vinayak2410/practice-11:latest -f practice-11/Dockerfile ."
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'vinayak2410', passwordVariable: '24102002@Vm')]) {
                        sh "echo 24102002@Vm | docker login -u vinayak2410 --password-stdin"
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh "docker push vinayak2410/practice-11:latest"
                }
            }
        }
    }

    post {
        always {
            script {
                sh 'docker rmi vinayak2410/practice-11:latest || true'
            }
        }
    }
}
